package edu.kennesaw.matchmakerservice.datamodel;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "PlayerInfo")
public class PlayerInfo {
    private String id;
    private String gamerId;
    private String firstName;
    private String lastName;
    private String skillLevel;
    private String region;
    private String language;
    private String personalityType;
    private String minimumWaitTime;
    private String game;
    private String gameMode;
    private List<String> friendsList;
    private List<String> groupsList;

    public PlayerInfo(){}


    public PlayerInfo(String gamerId, String firstName, String lastName, String skillLevel, String region, String language, String personalityType, String minimumWaitTime, String game, String gameMode) {
        this.gamerId = gamerId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.skillLevel = skillLevel;
        this.region = region;
        this.language = language;
        this.personalityType = personalityType;
        this.minimumWaitTime = minimumWaitTime;
        this.game = game;
        this.gameMode = gameMode;
    }

    public PlayerInfo(String gamerId, String firstName, String lastName, String skillLevel, String region, String language, String personalityType, String minimumWaitTime, String game, String gameMode, List<String> friendsList, List<String> groupsList) {
        this.gamerId = gamerId;
        this.firstName = firstName;
        this.lastName = lastName;
        this.skillLevel = skillLevel;
        this.region = region;
        this.language = language;
        this.personalityType = personalityType;
        this.minimumWaitTime = minimumWaitTime;
        this.game = game;
        this.gameMode = gameMode;
        this.friendsList = friendsList;
        this.groupsList = groupsList;
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    @DynamoDBAttribute
    public String getGamerId() {
        return gamerId;
    }

    @DynamoDBAttribute
    public String getFirstName() {
        return firstName;
    }

    @DynamoDBAttribute
    public String getLastName() {
        return lastName;
    }

    @DynamoDBAttribute
    public String getSkillLevel() {
        return skillLevel;
    }

    @DynamoDBAttribute
    public String getRegion() {
        return region;
    }

    @DynamoDBAttribute
    public String getLanguage() {
        return language;
    }

    @DynamoDBAttribute
    public String getPersonalityType() {
        return personalityType;
    }

    @DynamoDBAttribute
    public String getMinimumWaitTime() {
        return minimumWaitTime;
    }

    @DynamoDBAttribute
    public String getGame() {
        return game;
    }

    @DynamoDBAttribute
    public String getGameMode() {
        return gameMode;
    }

    @DynamoDBAttribute
    public List<String> getFriendsList() {
        return friendsList;
    }

    @DynamoDBAttribute
    public List<String> getGroupsList() {
        return groupsList;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setGamerId(String gamerId) {
        this.gamerId = gamerId;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public void setSkillLevel(String skillLevel) {
        this.skillLevel = skillLevel;
    }

    public void setRegion(String region) {
        this.region = region;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public void setPersonalityType(String personalityType) {
        this.personalityType = personalityType;
    }

    public void setMinimumWaitTime(String minimumWaitTime) {
        this.minimumWaitTime = minimumWaitTime;
    }

    public void setGame(String game) {
        this.game = game;
    }

    public void setGameMode(String gameMode) {
        this.gameMode = gameMode;
    }

    public void setFriendsList(List<String> friendsList) {
        this.friendsList = friendsList;
    }

    public void setGroupsList(List<String> groupsList) {
        this.groupsList = groupsList;
    }

    @Override
    public String toString() {
        return "PlayerInfo{" +
                "id='" + id + '\'' +
                ", gamerId='" + gamerId + '\'' +
                ", firstName='" + firstName + '\'' +
                ", lastName='" + lastName + '\'' +
                ", skillLevel='" + skillLevel + '\'' +
                ", region='" + region + '\'' +
                ", language='" + language + '\'' +
                ", personalityType='" + personalityType + '\'' +
                ", minimumWaitTime='" + minimumWaitTime + '\'' +
                ", game='" + game + '\'' +
                ", gameMode='" + gameMode + '\'' +
                ", friendsList=" + friendsList +
                ", groupsList=" + groupsList +
                '}';
    }
}
